# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}


def teardown_method(self, method):
    self.driver.quit()


def test_createDataset(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1083, 787)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
    assert self.driver.switch_to.alert.text == "Item added to cart."
    self.driver.find_element(By.ID, "add-to-cart-67").click()
    assert self.driver.switch_to.alert.text == "Item added to cart."
    self.driver.find_element(By.CSS_SELECTOR, ".feather-shopping-cart").click()
    self.driver.find_element(By.ID, "create-dataset-btn").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("Example3")
    self.driver.find_element(By.ID, "desc").click()
    self.driver.find_element(By.ID, "desc").send_keys("Example3")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    assert self.driver.switch_to.alert.text == "Dataset created successfully!"
