# Generated by Selenium IDE
from selenium.webdriver.common.by import By

from core.environment.host import get_host_for_selenium_testing
from core.selenium.common import initialize_driver


class TestPixcheckertest:
    def setup_method(self, method):
        self.driver = initialize_driver()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_pixcheckertest(self):
        self.driver.get(get_host_for_selenium_testing())
        self.driver.set_window_size(1854, 1048)
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
        self.driver.find_element(By.ID, "btnGroupDrop10").click()
        self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
        self.driver.find_element(By.ID, "btnGroupDrop11").click()
        self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
